### ISSUE TITLE
An interface for Lie groups

### ISSUE THREAD

**Issue by kellertuer** [JuliaNLSolvers/Manifolds.jl#1]
I think a good way to handle Lie group is with a `Trait`, i.e. the manifold gets a `LieGroup` trait (maybe also the points and vectors?) may be `⊗` or `◦`, and one could then think about how to  model the Lie algebra.

**Comment by sdaxen** [comment]
For some manifolds, it makes sense to assign it as a Lie group with a trait. e.g. SO(n) is pretty much always considered as both a Lie group and a manifold (i.e. there's no notation for a manifold underlying the group). But S1 is usually only considered a group T=U(1) when equipped with complex multiplication, and S3 is considered a group Sp(1) with quaternion multiplication. It seems a bit ugly to just make S3 a group by default, so maybe Sp(1) should just be a separate manifold, but then how do we avoid excessive code duplication? I imagine this will come up a lot when dealing with isomorphic manifolds/groups.

What if we had an `AbstractLieGroup` manifold with subtypes `NativeLieGroup` and `DerivedLieGroup`? `DerivedLieGroup` would wrap a `Manifold` `m` and operator `o` and forward the general `Manifold` interface functions to `m`. `NativeLieGroup` would be used for specifying manifolds like SO(n) and would implement those operators directly.

**Comment by mateuszbaran** [comment]
A natural way to represent different Lie group structures for the same manifold would be, in my opinion, to have a separate abstract type `AbstractLieGroup`, and then, for each particular group, a concrete type, like
```
struct SpecialOrthogonal{M<:Rotations} <: AbstractLieGroup
    manifold::M
end
```
and then have methods like `group_operation(so::SpecialOrthogonal, r1, r2)` or `inverse(so::SpecialOrthogonal, r)`. Lie group actions would have a completely separate abstract class as well. Manifold operation could be naturally handled by using the `manifold` field.

**Comment by kellertuer** [comment]
I don't like too much inheritance, that's too restrictive, i.e. a `NativeLieGroup` is then not able to be also a `NativeMatrixManifold` if we subtype that, too. 

But I like the decorator idea @mateuszbaran ! in fact, the ' Power` and `Product` and `TangentBundle`manifolds also have the same point of an internal manifold that is decorated/extended.

The only thin I would add is easy fall backs, i.e.
`exp(M::SpecialOrthogonal,x,v) = exp(M.manifold,x,v)`
and such, but that would not cover much more than a usual manifold anyways.
And yes, of course for `AbstractLieGroups` the `inverse`. Neat approach!

**Comment by sdaxen** [comment]
I also like this approach.

> The only thin I would add is easy fall backs, i.e.
`exp(M::SpecialOrthogonal,x,v) = exp(M.manifold,x,v)`
and such, but that would not cover much more than a usual manifold anyways.

The Riemannian exponential with metric G and Lie exponential are only equivalent if G is a bi-invariant metric on the group, and such a metric in many cases doesn't exist. So I wouldn't add fallbacks like these. If the user wants a Riemannian exponential, they'll need to explicitly choose a metric (see #9). We can provide some common ones like that from the Killing form, etc.

Matrix Lie groups should be their own abstract type, since they have some general properties we can define.
```julia
abstract type AbstractMatrixLieGroup <: AbstractLieGroup end

vee(M::AbstractMatrixLieGroup, V) = error("not defined")
hat(M::AbstractMatrixLieGroup, v) = error("not defined")
exp!(M::AbstractMatrixLieGroup, X::AbstractMatrix, V::AbstractMatrix) = X .= LinearAlgebra.exp(V)
exp!(M::AbstractMatrixLieGroup, X::AbstractMatrix, v::AbstractVector) = X .= exp(M, hat(v))
log!(M::AbstractMatrixLieGroup, V::AbstractMatrix, X::AbstractMatrix) = V .= LinearAlgebra.log(X)
log!(M::AbstractMatrixLieGroup, v::AbstractVector, X::AbstractMatrix) = v .= vee(LinearAlgebra.log(X))
```

although ideally without so much specialization.

**Comment by sethaxen** [comment]
With #68, this has been implemented.
