### ISSUE TITLE
Make equations more REPL-friendly

### ISSUE THREAD

**Issue by sethaxen** [JuliaNLSolvers/Manifolds.jl#101]
The primary goal with the equations is to render correctly in the HTML documentation. However, when the equations are pure LaTeX, they are tough to read in the unicode, and those who are reading the code offline or using the help feature in the REPL will have a hard time reading the equations without TeX rendering software.

In my PRs, I started using unicode characters when possible. i.e., when the unicode character renders identically to the TeX character in the HTML (tested on Google Chrome). For example,

https://github.com/JuliaNLSolvers/Manifolds.jl/blob/115b3532b21892a1a4e273d98c35f99a883666b2/src/groups/group.jl#L445-L457

which renders as [though it were completely written in LaTeX](https://julianlsolvers.github.io/Manifolds.jl/latest/manifolds/group.html#Manifolds.translate_diff-Tuple{Manifold,Any,Any,Any}).

There are a few downsides to this approach I can think of. First, the resulting equations can't just be pasted into a TeX renderer. Also, it is always possible that the user is using an OS or a browser with a font that does not contain those unicode characters. I think the positives outweigh the negatives though and propose adopting this convention across the package.

**Comment by mateuszbaran** [comment]
For me such mixed Unicode/LaTeX isn't much easier to read than pure LaTeX but I can see that it can help sometimes. I think we can adopt this convention.

**Comment by kellertuer** [comment]
I can read LaTeX nearly as if were rendered (or to cite a movie “after some time you just see the red dress”) – but I am fine with the UTF8 idea, we can do a browser check later and let'S hope enough browsers play that game.

**Comment by kellertuer** [comment]
Since we are discussion notations anyways: Maybe it's a good idea to have an overview of notation? There are quite a lot of different ways, notation is used on manifolds, for example I (otherwise, usually) use `p,q,x,y,z` for points, `X,Y,Z,W` for tangents, small greeks for cotangents, capital caligraphic for manifolds and so on. We are different here on tangents (being small letters), that's fine. But with a notation table we can also stay consistent in the docs.

**Comment by mateuszbaran** [comment]
Right, we're a bit inconsistent about notation. I think we should have a documentation page that explains it.
