### ISSUE TITLE
Add Methods for Embedding Manifolds and Working within embeddings.

### ISSUE THREAD

**Issue by kellertuer** [JuliaNLSolvers/Manifolds.jl#107]
While checking documentation, I noticed that two manifolds we nearly have despite `check`s, so nearly as easy as the torus, see, https://www.manopt.org/tutorial.html#manifolds, namely Symmetric and Skew Symmetric Matrices with Euclidean Metric. I think we have a few possibilities here

My first thought was to do an `AbstractEuclidean` manifold such that one can easily implement metric and such on that, but then I thought:

A more general approach would be nice, a framework for embedding and isometrically embedding manifolds. Here having the otherwise simple `Euclidean` really starts to make sense, but it would also work for other submanifolds, maybe even quotients. I propose:

* a function `getEmbedding(M,eT)` that has a second (optional) argument `EmbeddingType`, which defaults to `IsometricEmbedding`. So for `getEmbedding(Sphere(2))` you would get `Euclidean(3)`
* a function `embed(M,N,p)` that takes `p` from `M` and returns its representation within the embedding. For the Sphere this would be the identity. For FixedRankMatrices embedded in R^{nxm} this would transform the 3-factor-representation to just the matrix.
* the inverse would – I think – just be `project` but we could enhance that such that `project_point(M,x)` defaults to `project(M,N,x)`, i.e. project `x` from the embedding `N` to `M` and similarly for tangents
* we could also do a THTT again with `is_default_embedding(M,N)` or `is_default_isometric_embedding`, i.e. one can just use the metric from the embedding `N` for `M`, too.

This way – coming back to the SymmetricMatrices and SkewSymmetricMatrices one could implement them as `AbstractEmbeddedManifolds`, where any operation (exp,log,norm,...) would just boil down to `embed - fct - project`, where (with the idea that the outer two are here just identity, but one could also invent more clever representations then).

What to you think?

**Comment by mateuszbaran** [comment]
That is the main issue that delayed our support for complex coefficient ONBs and caused some trouble in other places. I think we definitely need some functions for working with embeddings.

A few comments:
* I'm not quite convinced by the function `get_embedding`. Until now I assumed that if a manifold is represented using an embedding, this embedding is essentially a part of that manifold, so you'd need a decorator to change it (we don't do that yet). So then we would have `get_embedding(M)` that derives type of the embedding from `M` itself.
* I like the idea of `embed` and `project`.
* I'm afraid `IsometricEmbedding` isn't specific enough. It has two problems: it doesn't specify the ambient space and usually we have either zero or infinitely many isometric embeddings. I'd just call the default embedding `DefaultEmbedding` and that's it.
* Fixed rank matrices is an interesting case. I think it motivates a slightly different interface. Using a different embedding will usually result in a different representation of points and tangent vector, so to me it looks like many functions need to be aware of which embedding is used. Maybe it would make sense to get rid of `EmbeddingType` and use manifold decorators to change the representation? `AbstractEmbeddedManifold` could be such decorator.

**Comment by kellertuer** [comment]
To the first point, you can embedd a manifold differently: For example the SPDs are embedded in R^nxn, but with a different metric. You can, however (and I don't remmber the details) embed the SPDs in an even bigger space isometrically.
So it is not a unique embedding you have, but you will have embeddings with a property (hence the idea of `isometricEmbedding` as a type. Yes its not specific enough, but there should be a smallest space you can embed into where its isometric. I am not 100% sure.

Ah despite an `EmbeddingType` one could introduce `EmbeddedManifold` as a type coupling the two manifolds (manifold and its embeding), you mean? That's exactely what this thread is for – find a good interface for that and yes, the type might not be the best choice, I am not yet sure.

**Comment by mateuszbaran** [comment]
> Ah despite an `EmbeddingType` one could introduce `EmbeddedManifold` as a type coupling the two manifolds (manifold and its embeding), you mean? That's exactely what this thread is for – find a good interface for that and yes, the type might not be the best choice, I am not yet sure.

Yes, I think introducing a type that can be used to couple a manifold with an embedding would be useful. It could specify a metric using embed-fct-project like you said.

**Comment by kellertuer** [comment]
will try that after the doc utf8 rework then and see where it leads.
