### ISSUE TITLE
Ideas for a Logo

### ISSUE THREAD

**Issue by kellertuer** [JuliaNLSolvers/Manifolds.jl#21]
Now that we have a new name, maybe we could also think about a Logo. One of my ideas (that I had for Manopt.jl actually but then they were missing the opt-part, so I am working on something different there), is, to use the “three Julia dots” and their colors to represent a manifold each, but I am not a designer so I did not get that far. The three manifolds I had in mind are

* top left a sphere (well that's obvious) with geodesics
* top right a hyperbolic space (maybe also in the embedding, so the H2 in R3 ?) but I haven't found a good way to illustrate that
* bottom center the Euclidean space, a square with straight vertical and horizontal lines (so R2), one could also do a cube to illustrate R3.

What do you think? Do you have a good way to illustrate that? I can try to do that in TikZ, though there the sphere might be tricky, since tikz is mainly good for 2D graphics, not for 3D (Especially not for occlusion things).

**Comment by mateuszbaran** [comment]
Julia project logos are usually quite simple and flat. Maybe we could use some nice tilings in Julia colors https://en.wikipedia.org/wiki/Uniform_tilings_in_hyperbolic_plane ?

**Comment by kellertuer** [comment]
While they look nice, my only objection is, that that's only one manifold, and our package has now the plural s included.

**Comment by sdaxen** [comment]
I like the idea of something flat and simple that conveys either the idea that this is a collection of manifolds or some representative aspect of generic manifolds that we provide.

**Comment by kellertuer** [comment]
I just had a short idea for a logo yesterday night that I just finished in dark and bright mode (since I am using GitHub in dark mode these days and the docs also have dark mode). May main idea is: Keep the Julia dots and present just main things we have. Currently tangent vectors and geodesics. We could add (in blue or white/black) small neat features to the other dots; maybe a slightly bending distribution?

![logo_dark](https://user-images.githubusercontent.com/115566/73061553-bde4de00-3e9a-11ea-89fd-9619e384b492.png)
![logo_bright](https://user-images.githubusercontent.com/115566/73061558-bfaea180-3e9a-11ea-8776-3ffc1fee9821.png)

For compilation you need Tamil MN as font and XeteX (or disable the last draw) in the code

````latex

\documentclass[tikz]{standalone}
\usepackage{}
\usepackage{ifthen}
\usepackage{fontspec}
\setmainfont{Tamil MN}
\usetikzlibrary{arrows.meta}
\newboolean{darkmode}
\setboolean{darkmode}{false}
\definecolor{jblue}{rgb}{0.255, 0.412, 0.882}
\definecolor{jred}{rgb}{0.804, 0.2, 0.2}
\definecolor{jgreen}{rgb}{0.133, 0.545, 0.133}\usepackage{ifthen}
\definecolor{jpurple}{rgb}{0.706, 0.322, 0.804}

\tikzset{blob/.style={fill opacity=0.95, circle, minimum size=1cm,thick}}
\tikzset{blobred/.style={fill=jred, draw=jred, blob}}
\tikzset{blobpurple/.style={fill=jgreen, draw=jgreen, blob}}
\tikzset{blobgreen/.style={fill=jpurple, draw=jpurple, blob}}

\tikzset{geodesic/.style={very thick,black,cap=round}}
\tikzset{tangent/.style={thick,jblue,->,>={Stealth[round]} }}

\ifthenelse{\boolean{darkmode}}{%
\tikzset{geodesic/.style={very thick,white,cap=round}}
\pagecolor{black!95}
}
\begin{document}
    \begin{tikzpicture}[scale=2]
        \draw[geodesic] (-0.5,0.0) node (a) {} (0.5,0.0) node (b) {} (0.0, {sqrt(3)/4}) node (c) {};
        \draw[geodesic] (c.center) .. controls (-0.2,{sqrt(3)/4}) and (-0.5,0.2) .. (a.center);
        \draw[geodesic] (c.center) .. controls (0.2,{sqrt(3)/4}) and (0.5,0.2) .. (b.center);
        \draw[geodesic] (a.center) to [bend right=30] (b.center);
        \draw (a) node[blobred] {};
        \draw (b) node[blobpurple] {};
        \draw (c) node[blobgreen] {};
        \draw[tangent] (c.center) -- ++ (0.5,0);
        \draw (0.0,-0.4) node (T) {%
            \ifthenelse{\boolean{darkmode}}{\color{white}}{}
            \large\bfseries Manifolds.jl
        };
    \end{tikzpicture}
\end{document}
````

I tried getting the image a little more 3D ish by using ellipses instead of circles for the dots, but that just looked ugly. What do you think? Yes it's not a hyperbolic plane I know; one could try geodesics with that, too, but I haven't done that yet.

**Comment by mateuszbaran** [comment]
Looks very nice!

One thing I'd change are the dots, Julia logo doesn't use borders with different colors now, see here: https://github.com/JuliaLang/julia-logo-graphics . The colors should also be slightly different (I think you used the "nearest named color" values).

> We could add (in blue or white/black) small neat features to the other dots; maybe a slightly bending distribution?

You mean like a bending normal distribution pdf? Good idea. Maybe we could have some arrows like these: https://depositphotos.com/294302506/stock-illustration-arrow-rotation-icon-in-transparent.html in the third dot to represent rotation action? I wouldn't like it to be too cluttered though.

**Comment by kellertuer** [comment]
I copied the rgb values from the Julia docs, so I am not sure what you mean by nearest named,... but yes they are currently slightly transparent in order to see all of the geodesic, so that might be different.

maybe a bending pdf is a little hard to generate so one could also fill a tangent space (dot) with a pdf. Rotation for gourp/lie is an idea though I am not sure that icon might be the one to recognise that.

**Comment by mateuszbaran** [comment]
> I copied the rgb values from the Julia docs, so I am not sure what you mean by nearest named,... but yes they are currently slightly transparent in order to see all of the geodesic, so that might be different.

Where did you find these values in Julia docs? I've looked at this image from the repository I've linked in the previous message: https://github.com/JuliaLang/julia-logo-graphics/blob/master/images/julia-colors.svg

> maybe a bending pdf is a little hard to generate so one could also fill a tangent space (dot) with a pdf. Rotation for gourp/lie is an idea though I am not sure that icon might be the one to recognise that.

Good point, we could try something else.

**Comment by kellertuer** [comment]
Yes, I had hoped that the `rgb(...)` values are the ones you see in the code above (hoping that I did not mistype them).

**Comment by kellertuer** [comment]
Without opacity I feel one does not get the feeling on non-linearity/bended-ness: one with just opaque dots, one with geodesics up front (but a boundary to still tell that the tangent plane is kind of atop...)
![logo_bright3](https://user-images.githubusercontent.com/115566/73066762-2934ad00-3ea7-11ea-94d8-ff2eb08e9f1d.png)
![logo_bright2](https://user-images.githubusercontent.com/115566/73066760-28038000-3ea7-11ea-99e5-be6a59d91183.png)

**Comment by kellertuer** [comment]
Since `Base` is just the interface and simpler we could (wherever we need that) use something like the following for base: 
![logo_base](https://user-images.githubusercontent.com/115566/73067324-ab71a100-3ea8-11ea-8240-f39f31ac3071.png)
![logo_base_w](https://user-images.githubusercontent.com/115566/73067325-ac0a3780-3ea8-11ea-8549-c267c52d0e6d.png)

But with the tangent vector this looks then strange I think

**Comment by mateuszbaran** [comment]
I think the original idea was the nicest. I've slightly modified the colors to match what I think they should be:
```latex
\documentclass[tikz]{standalone}
\usepackage{}
\usepackage{ifthen}
\usepackage{fontspec}
\setmainfont{Tamil MN}
\usetikzlibrary{arrows.meta}
\newboolean{darkmode}
\setboolean{darkmode}{false}
\definecolor{jblue}{rgb}{0.251, 0.388, 0.847}
\definecolor{jred}{rgb}{0.796, 0.235, 0.2}
\definecolor{jgreen}{rgb}{0.22, 0.596, 0.149}\usepackage{ifthen}
\definecolor{jpurple}{rgb}{0.584, 0.345, 0.698}

\tikzset{blob/.style={fill opacity=1, circle, minimum size=1cm,line width=0pt}}
\tikzset{blobred/.style={fill=jred, draw=jred, blob}}
\tikzset{blobpurple/.style={fill=jgreen, draw=jgreen, blob}}
\tikzset{blobgreen/.style={fill=jpurple, draw=jpurple, blob}}

\tikzset{geodesic/.style={very thick,black,cap=round}}
\tikzset{geodesic2/.style={very thick,black,cap=round,opacity=0.05}}
\tikzset{tangent/.style={thick,jblue,->,>={Stealth[round]} }}

\ifthenelse{\boolean{darkmode}}{%
\tikzset{geodesic/.style={very thick,white,cap=round}}
\pagecolor{black!95}
}
\begin{document}
    \begin{tikzpicture}[scale=2]
        \draw[geodesic] (-0.5,0.0) node (a) {} (0.5,0.0) node (b) {} (0.0, {sqrt(3)/4}) node (c) {};
        \draw[geodesic] (c.center) .. controls (-0.2,{sqrt(3)/4}) and (-0.5,0.2) .. (a.center);
        \draw[geodesic] (c.center) .. controls (0.2,{sqrt(3)/4}) and (0.5,0.2) .. (b.center);
        \draw[geodesic] (a.center) to [bend right=30] (b.center);
        \draw (a) node[blobred] {};
        \draw (b) node[blobgreen] {};
        \draw (c) node[blobpurple] {};

        \draw[geodesic2] (c.center) .. controls (-0.2,{sqrt(3)/4}) and (-0.5,0.2) .. (a.center);
        \draw[geodesic2] (c.center) .. controls (0.2,{sqrt(3)/4}) and (0.5,0.2) .. (b.center);
        \draw[geodesic2] (a.center) to [bend right=30] (b.center);

        \draw[tangent] (c.center) -- ++ (0.5,0);
        \draw (0.0,-0.4) node (T) {%
            \ifthenelse{\boolean{darkmode}}{\color{white}}{}
            \large\bfseries Manifolds.jl
        };
    \end{tikzpicture}
\end{document}
```
What do you think?

BTW, I don't think `ManifoldsBase.jl` needs a separate logo.

**Comment by kellertuer** [comment]
Nice idea to tweak the colors to get for the transparent ones the original color (roughly) though that might be different for dark and bright? Haven't checked.

The Base was just a short idea, maybe you're right and we don't need that, yes.

So we would “just” need ideas for the two remaining tangent spaces.

**Comment by kellertuer** [comment]
I just changed what I just proposed, to do the light curves (geodesic2 atop) in white in dark mode, the result is

![logo_black](https://user-images.githubusercontent.com/115566/73076944-76bd1400-3ebf-11ea-9d7f-0130f464b7ce.png)

The code is not that different, will post that when we have stuff for red and green tangent spaces.

**Comment by kellertuer** [comment]
So I changed your idea a little bit and did the following: 

````tex
\documentclass[tikz]{standalone}
\usepackage{ifthen, fontspec, fontawesome5}
\setmainfont{Tamil MN}
\usetikzlibrary{arrows.meta}
\newboolean{darkmode}
\setboolean{darkmode}{true}
\ifthenelse{\boolean{darkmode}}{%
    \definecolor{fgc}{rgb}{1.0, 1.0, 1.0}
    \definecolor{bgc}{rgb}{0.0,0.0,0.0}
}{%
    \definecolor{fgc}{rgb}{0.0, 0.0, 0.0}
    \definecolor{bgc}{rgb}{0.9, 0.9, 0.9}
}
\definecolor{jblue}{rgb}{0.251, 0.388, 0.847}
\definecolor{jred}{rgb}{0.796, 0.235, 0.2}
\definecolor{jgreen}{rgb}{0.22, 0.596, 0.149}
\definecolor{jpurple}{rgb}{0.584, 0.345, 0.698}

\tikzset{blob/.style={circle, minimum size=1cm,line width=0pt}}
\tikzset{blobred/.style={fill=jred, draw=jred, blob}}
\tikzset{blobpurple/.style={fill=jgreen, draw=jgreen, blob}}
\tikzset{blobgreen/.style={fill=jpurple, draw=jpurple, blob}}

\tikzset{geodesic/.style={very thick,fgc,cap=round}}
\tikzset{geodesic2/.style={very thick,fgc,cap=round,opacity=0.05}}
\tikzset{tangent/.style={very thick,jblue,->,>={Stealth[round]} }}

\pagecolor{bgc}

\begin{document}
    \begin{tikzpicture}[scale=2]
        \draw[geodesic] (-0.5,0.0) node (a) {} (0.5,0.0) node (b) {} (0.0, {sqrt(3)/4}) node (c) {};
        \draw[geodesic] (c.center) .. controls (-0.2,{sqrt(3)/4}) and (-0.5,0.2) .. (a.center);
        \draw[geodesic] (c.center) .. controls (0.2,{sqrt(3)/4}) and (0.5,0.2) .. (b.center);
        \draw[geodesic] (a.center) to [bend right=30] (b.center);
        \draw (a) node[blobred] {};
        \draw (b) node[blobgreen] {};
        \draw (c) node[blobpurple] {};

        \draw[geodesic2] (c.center) .. controls (-0.2,{sqrt(3)/4}) and (-0.5,0.2) .. (a.center);
        \draw[geodesic2] (c.center) .. controls (0.2,{sqrt(3)/4}) and (0.5,0.2) .. (b.center);
        \draw[geodesic2] (a.center) to [bend right=30] (b.center);

        \draw[tangent] (c.center) -- ++ (0.5,0);
        \draw (a) node {\large\color{jblue}\faIcon{undo-alt}};
        \draw (0.0,-0.45) node (T) {\color{fgc}\large\bfseries Manifolds.jl};
    \end{tikzpicture}
\end{document}
````
which yields

![logo_black](https://user-images.githubusercontent.com/115566/73078447-77a37500-3ec2-11ea-806b-6ea6d7cc17c9.png)

since I noticed that the sphere we sketch and we add rotation around the vector pointing on the sphere you get rotations which _is_ a Lie group, so this indicates bot a second manifold as well as Lie groups. I don't like the blue yet, but that's fine-tuning. in the green spot we should illustrate somehow illustrations or maybe parallel/vector transport.

**Comment by kellertuer** [comment]
I had a short idea to just do a 2d Gaussian distribution sampling (500 samples currently) for the last part; that's just a few lines in Julia and an export to csv, loaded and scatter-plotted with pgfplots – ... here's the result (changed colors a little bit) – now waiting for feedback also from Seth.
![logo_d](https://user-images.githubusercontent.com/115566/73087428-ca852880-3ed2-11ea-95a2-f7ddfd22c091.png) ![logo_b](https://user-images.githubusercontent.com/115566/73087439-cc4eec00-3ed2-11ea-9f09-9ec80458beee.png)

**Comment by mateuszbaran** [comment]
I like the last version, I think we can use it :+1: .
