### ISSUE TITLE
Setting up CI and code coverage

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaNLSolvers/Manifolds.jl#26]
I think it would be good to set up CI and code coverage (Travis, AppVeyor, Coveralls or Codecov) for this project. I've looked at it and it seems that it needs to be done by someone from the JuliaNLSolvers org. @antoine-levitt , could help a bit with this?

**Comment by antoine-levitt** [comment]
I can but I don't know what to do. @pkofod did this for the old Manifolds I believe? Code coverage is one of those good-ideas-in-theory that's mostly annoying in practice so I would not bother.

**Comment by pkofod** [comment]
I can do it. We need scripts in the top level folder for the CIs we want, and then I need to enable them. Coverage is nice, but as Antoine says, it's often super imprecise.

**Comment by mateuszbaran** [comment]
Thanks! I've added a config file for AppVeyor.

I've had relatively good experience with code coverage in CovarianceEstimation.jl but yes, it's far less useful than CI.

**Comment by kellertuer** [comment]
Thanks for setting that up. I might be one of the guys reminding people to get better code coverage, since I really prefer to easily checks whether “everything still works”(tm) after I change something.

**Comment by pkofod** [comment]
I should have set up AV now.

**Comment by kellertuer** [comment]
Despite the documentation not being pushed somewhere – isn't this nearly resolved?

**Comment by sdaxen** [comment]
I think it is now. Is it easy to get documentation pushed?

**Comment by kellertuer** [comment]
I think (when e.g. we use a `gh-pages`-branch here) it should be just the lines like
```
deploydocs(
    repo   = "github.com/kellertuer/Manopt.jl",
    devbranch = "development"
)
```
(that I just copied from `Manopt.jl`) as well as a SSH-Key that provides push access that is added to this repo and the travis settings, see https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#SSH-Deploy-Keys-1

**Comment by kellertuer** [comment]
Can this be closed here? I think the documentation is published correctly and the travis and code coverage also works just fine :)

**Comment by mateuszbaran** [comment]
Yes, I'll close it now.
