### ISSUE TITLE
More numerically stable geodesic integration on 32-bit Windows

### ISSUE THREAD

**Issue by sethaxen** [JuliaNLSolvers/Manifolds.jl#29]
It seems that these tests easily fail on 32-bit Windows:
https://github.com/JuliaNLSolvers/Manifolds.jl/blob/1de7ef78cc5cf4d4731c43fedfaa5d79d1fd9877/test/metric_test.jl#L93-L96 See for example [this failed build on AppVeyor](https://ci.appveyor.com/project/pkofod/manifolds-jl/builds/25794478/job/w2cajaccp0smf6mj). I don't have much experience with `OrdinaryDiffEq.jl`, but the required tolerance of the test seems quite reasonable. Does anyone have recommendations for how to stabilize these? Perhaps a symplectic integrator?

**Comment by kellertuer** [comment]
I ran unto a similar problem with SPDs, increasing the `is_approx` tolerance by a factor of 2 did the job for the too inexact eigen values on 32 bit (error was of size `8*10^-16` insead of just `4*10^-16`.

**Comment by mateuszbaran** [comment]
I think this was resolved some time ago by not supporting 32-bit Windows at all. I think we can close this issue since fixing it is not planned.
