### ISSUE TITLE
Random points and vectors.

### ISSUE THREAD

**Issue by kellertuer** [JuliaNLSolvers/Manifolds.jl#3]
In order to construct random points and vectors we have to find a way to specify the kind of randomness. For example tangent vectors of SPDs can be generated using Gaussian or Rician noise. For me that is independent of a manifold, i.e. should not be a field of `manifold` but maybe an optional parameter to the random functions? Maybe something like

`random_vector(M,x,:Gaussian,sigma)`

and

`random_vector(M,x,:Rician,tau)`

where I am also not so sure, whether other kinds of noise might even require more parameters.

the default `random_point(M,x)` should then be set to a default noise with default parameters for example `:Gaussian` with `sigma=1`. What do you think?
dependent o

**Comment by sdaxen** [comment]
Many different distributions could be used to generate noise. A few off the top of my head would be uniform (for compact manifolds), tangent-X (for any X that can be defined on the tangent space), X (similar to tangent-X but with a Jacobian adjustment, i.e. it is not pulled back to the manifold), and Brownian diffusion.

I'm okay with just assuming tangent-X and passing the corresponding distribution (e.g. from Distributions.jl) to a function as syntactic sugar (i.e.. something like `random_vector(M,x,d) = exp(M,x,rand(d))`).

A separate package really should support more manifold statistics.

**Comment by kellertuer** [comment]
Passing down the distribution a second (`random_point`) or third (`random_vector`) is a very neat idea.

**Comment by sdaxen** [comment]
Oh sorry, that totally should have been `random_vector(M,x,d) = rand(d)`, `random_point(M,x,d) = exp(M,x,rand(d))`, potentially with the vectors wrapped in a special type if we do that.

RE your point in https://github.com/JuliaNLSolvers/ManifoldMuseum/issues/2#issuecomment-499385511, if we do have such custom types, those could be passed to these functions. But then it may make more sense to extend `Base.rand`.

**Comment by mateuszbaran** [comment]
I've quickly sketched a Distributions.jl-style interface for random points:
```julia
using Distributions

abstract type Manifold
end

struct ManifoldPointVariate <: VariateForm
end

struct ManifoldGaussian{TM<:Manifold, TMean, TSigma<:Real} <: Distribution{ManifoldPointVariate, Continuous} where TMean
    M::TM
    μ::TMean
    σ::TSigma
end

function rand(d::ManifoldGaussian)
end
```
Obtaining random points would then look like, for example, `rand(ManifoldGaussian(Sphere(), [1.0, 0.0, 0.0], 0.2))`. This would allow for easy interfacing with the Distributions.jl ecosystem.

**Comment by sdaxen** [comment]
This discussion is relevant: https://github.com/JuliaStats/Distributions.jl/issues/224.

I still feel that defining distributions on manifolds and methods for working with them would be outside the scope of this package and should instead be in its own (e.g. `ManifoldDistributions.jl`), but I'm open to it.

Also, if we use tangent-X, we should decide on the behavior if the random vector falls outside of the injectivity radius.

**Comment by pkofod** [comment]
> I still feel that defining distributions on manifolds and methods for working with them would be outside the scope of this package and should instead be in its own (e.g. `ManifoldDistributions.jl`), but I'm open to it.

While that may be true, I think many people will agree that "premature splitting of functionality is the root of all headaches" in the sense that you then have to worry about versions, tests being out of date in one package so you're not catching errors right away, etc.

My advice would be to try it out here, and if it turns out that it's easier to maintain in a separate package, but after the general interface and functionality has settled, it can be moved out into its own package.

**Comment by sethaxen** [comment]
For now, we have decided to include distributions in this package. Further discussion on that implementation can continue in #57.
