### ISSUE TITLE
Structure Code & References in Documentation

### ISSUE THREAD

**Issue by kellertuer** [JuliaNLSolvers/Manifolds.jl#32]
I noticed two things we do differently in coding
(1) until now I always wrote `export`, `using/import`s at the beginning of a file, kind of like a table of contents, now we have a little bit of a mix, since some files contain the exports at the end
(2) Since we collect all functions for a manifold in a file, wouldn't it be nice to order functions alphabetically? I can just rearrange everything, but I'd like to have an opinion what you think about this

Furthermore, I'd like to provide references for formulae, not necessarily in single function documentations, but especially on the documentation page of a manifold (I also started to illustrate SPDs with an image in #27). Is there a preferred way how to do references? For example we could try `BibTeX.jl` but for now I just did a markdown list, see e.g. http://www.manoptjl.org/stable/solvers/cyclicProximalPoint/#Literature-1). The advantage of something more automated would be a more consistent format than the manual list.

**Comment by sdaxen** [comment]
> (1) until now I always wrote `export`, `using/import`s at the beginning of a file, kind of like a table of contents, now we have a little bit of a mix, since some files contain the exports at the end

I've only ever written packages with all of the imports/exports in the main source file, though I can see the clarity for doing it in each file. Is there a nice way to test that all the right imports/exports are there?

> (2) Since we collect all functions for a manifold in a file, wouldn't it be nice to order functions alphabetically? I can just rearrange everything, but I'd like to have an opinion what you think about this

An alternative to ordering alphabetically that we've sort of being doing is ordering by related functionality. So `exp` and `log` are together, with `retract` near `exp`. `inner`, `norm`, `distance`, etc all go together so that it's easy to switch back and forth while developing.

That being said, while that approach may make the code clearer, it does nothing for the API documentation, which is alphabetical. Perhaps it is a better idea to sort alphabetically and frequently use `@ref`.

A compromise would be to have common sections for each manifold, and then within each section they're alphabetized. I guess I don't have a strong preference, so long as we're consistent.

👍 for documenting references. I like the idea of an automated approach that reads from a source bibtex file. Is that what `BibTeX.jl` does?

**Comment by kellertuer** [comment]
> I've only ever written packages with all of the imports/exports in the main source file, though I can see the clarity for doing it in each file. Is there a nice way to test that all the right imports/exports are there?

I don't think there is – I just read that somewhere so I did that for now that way, so my inner files just start with `using` and `imports` and then state all `exports`, i.e. functions this file defines or defines at leat a version for. I am not aware of a test, since basically it should be enough to have an `export exp` in the main file.

> That being said, while that approach may make the code clearer, it does nothing for the API documentation, which is alphabetical. Perhaps it is a better idea to sort alphabetically and frequently use `@ref`.

Grouping logically also sounds nice, but I was also more thinking about the documentation order and I prefer to use `@ref`s a lot anyways. My main point is also to get it consistent

 
> 👍 for documenting references. I like the idea of an automated approach that reads from a source bibtex file. Is that what `BibTeX.jl` does?

I haven't had the time to try BibTeX.jl`, also because it just has a few commits and I feared I might end up developing that before using it ;) but yes, one of my goals is to provide the user also with next literature to refer to for formulae and manifolds and such.

**Comment by sdaxen** [comment]
> I haven't had the time to try BibTeX.jl`, also because it just has a few commits and I feared I might end up developing that before using it ;) but yes, one of my goals is to provide the user also with next literature to refer to for formulae and manifolds and such.

Yeah, I just took a look at it, and it looks like it's not currently under active development (though it might be soon). Might be worth adopting the approach your used in `Manopt.jl` and switching when something more automated becomes available.

**Comment by mateuszbaran** [comment]
> (1) until now I always wrote `export`, `using/import`s at the beginning of a file, kind of like a table of contents, now we have a little bit of a mix, since some files contain the exports at the end

I think Manopt.jl is the only Julia library I've seen that doesn't put all exports and imports in the main file. I would like to have at least all imports of functions that are extended with new methods in the main file. I'm pretty indifferent about other imports and exports though.

> > (2) Since we collect all functions for a manifold in a file, wouldn't it be nice to order functions alphabetically? I can just rearrange everything, but I'd like to have an opinion what you think about this
> 
> An alternative to ordering alphabetically that we've sort of being doing is ordering by related functionality. So `exp` and `log` are together, with `retract` near `exp`. `inner`, `norm`, `distance`, etc all go together so that it's easy to switch back and forth while developing.

I was sort of trying to put related methods close but the code is short enough that I didn't really care that much about the order. It would definitely help to have a fixed order though. I think at least some degree of grouping by functionality would be advisable, for example types and methods related to distributions should go together.

> > I haven't had the time to try BibTeX.jl`, also because it just has a few commits and I feared I might end up developing that before using it ;) but yes, one of my goals is to provide the user also with next literature to refer to for formulae and manifolds and such.
> 
> Yeah, I just took a look at it, and it looks like it's not currently under active development (though it might be soon). Might be worth adopting the approach your used in `Manopt.jl` and switching when something more automated becomes available.

Isn't `Bibtex.jl` just a parser of bibtex files? I think the approach from `Manopt.jl` is good enough. Which bibliography style are you using there?

**Comment by kellertuer** [comment]
I actually do not completely know, where I got the style from to do exports also in subfiles, I'd have to check. But you're right, the main file should do, what you said.

Concerning `BibTeX.jl` – I also mainly saw that and planed to check soon, my hope was, that someone(tm) would just extend `Documenter.jl` to be able to handle something like `[citekey](@cite)` togeter with a BibTeX file or some other literature format (maybe a bibtex-type YAML file or something).

Currently I did the literature list itself as a `raw html` description list with a cite key consisting of the authors last names first letters and 2 digits for a year, and the entry itself is the authors `Lastname1, F1., Lastname2, F2.:` followed by the title in bold and the Journal reference in italics (but not abbreviated, full journal name), followed by details (volume, issue pages) as well as DOI and a link to a free version (arXiv). If there's just one author the key gets the authors last names first 3 letters and 2 digits for a year – though I just see, I did not do that consistently ;) (that's why it would be great to have an automatic way.

**Comment by mateuszbaran** [comment]
For now probably the best thing we can do with Documenter.jl are refs for citations where each bibliographical item has its own header. Not ideal but would work.

I almost never make bibliographical items by hand. I rely either on bibtex to do its job or the "create bibliography from item" option from Zotero (which apparently supports 9417 different styles). Personally I quite like the IEEE style but I can use any supported by Zotero.

**Comment by kellertuer** [comment]
While the new cool idea of @sethaxen is great, namely to use footnotes, currently that leads to warnings whenever two functions use the same reference/footnote that the footnote body is given twice. I don't know a solution to that yet, but just to document that here.

**Comment by sethaxen** [comment]
What if the footnote body is given once? Does that raise errors, and does the REPL docs include the footnote body in both docstrings?

**Comment by kellertuer** [comment]
If you only do the body once, the body also only shown up in REPL once since it'sonly printing the string and not looking through all docstrings for that footnote.

**Comment by kellertuer** [comment]
I shortly checked with the slack documentation group and I think with the restructuring in #74 I will go back to the blockquote approach. We can still collect Literature that is not explicitly mentioned in the Markdown file then.

**Comment by sethaxen** [comment]
> We can still collect Literature that is not explicitly mentioned in the Markdown file then.

You can do that with the existing approach. Just include the footnote body for the literature at the bottom of the page where you want it to be displayed. It will render like all the other footnotes. You'll just see a warning that it's unused.

The only downside to the current approach appears to be that we have to choose between no reference body for one docstring in the REPL mode or duplicate footnote bodies in the html docs. (https://github.com/JuliaDocs/Documenter.jl/issues/566 is the relevant issue) In my view those downsides are outweighed by the superior formatting of the footnote style in both modes, but that's just a preference, not a strong opinion.

**Comment by kellertuer** [comment]
I am still unsure which way to go. I don't think the blockquote approach is that bad, but you'Re right the footnotes being displayed at the bottom of the page is a nice feature (though misusing the footnotes a little bit). Ther referenced issue seems that Morten maybe aims to put footnotes in the dostring instead of collecting at the bottom.

Hm. So which way do we want to go? I can start rewriting the docs to above mentioned scheme (anyways) and we can refactor literature also later.

**Comment by sethaxen** [comment]
> Ther referenced issue seems that Morten maybe aims to put footnotes in the dostring instead of collecting at the bottom

Yeah, and tbh, that's probably a better way to go anyways. And I'd wager it wouldn't be that much work to make the necessary changes to Documenter, but I don't want to do it. 🙂 

> I don't think the blockquote approach is that bad, but you'Re right the footnotes being displayed at the bottom of the page is a nice feature (though misusing the footnotes a little bit).

No, blockquotes aren't terrible. I just didn't like how they worked for [`GeodesicInterpolation`](https://julianlsolvers.github.io/Manifolds.jl/latest/statistics.html#Manifolds.GeodesicInterpolation). i.e., in the text of the docstring, different manifolds/radii have different texts as references, and I liked being able to have a hyperlink that points to the article reference. I don't think I can link to a single reference within a blockquote. If you'd be more comfortable with the blockquote approach, I'm fine with that. I'd prefer it to be its own PR though so it's easier to revert it in the future if we choose. It was a mistake for me to make the switch in a PR with other things.

**Comment by kellertuer** [comment]
> No, blockquotes aren't terrible. I just didn't like how they worked for [`GeodesicInterpolation`](https://julianlsolvers.github.io/Manifolds.jl/latest/statistics.html#Manifolds.GeodesicInterpolation). i.e., in the text of the docstring, different manifolds/radii have different texts as references, and I liked being able to have a hyperlink that points to the article reference. I don't think I can link to a single reference within a blockquote.

I will see wether I'll feel the same or run into the same issue when porting and we can discuss in the PR anyways.

> If you'd be more comfortable with the blockquote approach, I'm fine with that. I'd prefer it to be its own PR though so it's easier to revert it in the future if we choose. It was a mistake for me to make the switch in a PR with other things.

Ok I will do a seperate second PR on that than, where I just change cites (after the first one is finished). Might take a day or two, the 36c3 was very nice, but also quite sleepless ;)

**Comment by kellertuer** [comment]
While our current approach produces doubles footnotes with same key, I would propose to close this (with finishing the #83) and wait for https://github.com/JuliaDocs/Documenter.jl/issues/1162.

**Comment by mateuszbaran** [comment]
Yes, we can solve the double footnote problem when that Documenter gets better support for bibliography.
