### ISSUE TITLE
Using `ProductArray` with large submanifold

### ISSUE THREAD

**Issue by sdaxen** [JuliaNLSolvers/Manifolds.jl#33]
It would be nice to be able to use `ProductArray` with some views not being a `SizedAbstractArray`. My use case is a `ProductManifold` with one thousands-dimensional Euclidean submanifold and other smaller submanifolds. It's not feasible to represent the part of the array corresponding to the Euclidean submanifold with a `SizedAbstractArray`, so I would like it to be a normal `Array`. I know `ProductMPoint` respects the type of representation, but I'm passing the product array to another package that expects an `AbstractArray` input.

I can already custom create a `ProductArray` with one of the parts being a normal `view`, but this is not respected whenever a new `ProductArray` is created; only the shape specification and underlying data array are used to create the new `ProductArray`.

Would it be a good idea to have some logic baked into the package so users don't accidentally try to create a 20,000-dimensional sized array like I did? I'm thinking also of some of the `MetricManifold` methods like `christoffel_symbols_first` that return sized arrays by default.

**Comment by mateuszbaran** [comment]
Very good point, I didn't think about that. I'll work on that soon.

**Comment by mateuszbaran** [comment]
Fixed by #34
