### ISSUE TITLE
How to access documentation 

### ISSUE THREAD

**Issue by baggepinnen** [JuliaNLSolvers/Manifolds.jl#36]
I'm just wondering how to access the documentation for this package. It looks like there's supposed to be something, but I can't find it hosted on julianlsolvers.github.io?

**Comment by mateuszbaran** [comment]
Someone from the JuliaNLSolvers org has to deploy it.
@pkofod , could you help?

**Comment by pkofod** [comment]
Yes, I'm not sure what needs to be done here. @fredrikekre - halp?

**Comment by mateuszbaran** [comment]
Deploying documentation is described here: https://juliadocs.github.io/Documenter.jl/stable/man/hosting/

The key part only org members can do is setting SSH keys in Travis.

**Comment by fredrikekre** [comment]
There is no call to `deploydocs` in `docs/make.jl` so docs are never deployed.

**Comment by mateuszbaran** [comment]
> There is no call to `deploydocs` in `docs/make.jl` so docs are never deployed.

Yes, that too, I can fix that.

**Comment by mateuszbaran** [comment]
OK, everything seems to be in place now except the key: https://travis-ci.org/JuliaNLSolvers/Manifolds.jl/jobs/587373091

**Comment by mateuszbaran** [comment]
Probably something wrong with the key:

> ERROR: The key you are authenticating with has been marked as read only.

When you add deploy keys you need to check the "Allow write access" option (on the screen where you enter the key and a title).

**Comment by pkofod** [comment]
Is it skipping because of the problems in the warnings? https://travis-ci.org/JuliaNLSolvers/Manifolds.jl/jobs/589126052

**Comment by fredrikekre** [comment]
Yes
