### ISSUE TITLE
Model real and complex valued Manifolds

### ISSUE THREAD

**Issue by kellertuer** [JuliaNLSolvers/Manifolds.jl#51]
I just noticed for FixedRank and Stiefel, that (see #49 ), that most functions directly apply for complex valued matrices as well, but a few also differ, for example (and most prominently) `manifold_dimension`. How shall we handle this?

Currently we have 2 different approaches

* `Euclidean` assumes all to be real-valued and only has its dimension as Type.
* `Stiefel` as the `eltype()` as a type transparently, so it is possible to directly write both `manifold_dimensions`

While one could introduce `ComplexEuclidean` I would prefer `Euclidean{n,T}`knowing its Eltype (or at least an idea of `Real` or `Complex`). What do you think? Especially for Euclidean there is just one line to add, I think (namely `manifold_dimension` to ne `2n` in the complex case).

**Comment by mateuszbaran** [comment]
I think it's fine to encode in a type parameter whether a manifold is complex or real when it can be both.

**Comment by sethaxen** [comment]
I agree that the type is a good way to go. I can think of real, complex, and quaternionic manifolds. Are there any others I'm missing?

**Comment by mateuszbaran** [comment]
I've read the description of quaternionic manifolds on Wikipedia and now I'm just confused. It's somehow not about charts but some G-structures on real manifolds with additional constraints? It sounds like a lot of work to support it.

**Comment by sethaxen** [comment]
Yeah I don't know anything about them except that Sp(1) is isomorphic to U(1,H). While the representation of with 2x2 complex matrices arises from common descriptions of Sp(1) and SU(2), the representation as unit quaternion arises from U(1,H).

Anyways, I don't think we need to support it, especially because there's no standard Quaternion type.

We might want to add a function that returns the type (field?) of the manifold, defaulting to the reals.

**Comment by kellertuer** [comment]
I think we can just keep `T` as a type of the manifold as soon as it has more then just the possibility of reals. If someone comes up with a type of Quaterions and is interested ineugh to implement a manifold – great!

Concerning the function I would propose `fieldtype` that defaults to `Real` ?
Maybe even in an advanced form:
`fieldtype(::Manifold) = Real` and `fieldtype(::Manifold,x) = eltype(x)` - so that one can even get a more precise answer?

With that I notice that my documentation got a little Germanised, since I wrote K={R,C} which should be F={R,C} (in german math (not otherwise) Körper is field - note that Körper translates to (human) body and field is Feld in German, referring to the agriculture one – these math guys!)

**Comment by sethaxen** [comment]
I like the `fieldtype` idea.  Regarding the version with `eltype`, I see a problem if the manifold is complex but the point happens to be real.

**Comment by kellertuer** [comment]
Oh, I had hoped for better types with the second idea, but the larger problem is not your case: with something like `Type(one(T)*one(x))` a real type of `x` and a complex manifold fit (x can be easily converted to complex) – the other way around would have to raise an error... so maybe we leave that out completely and just do `fieldtype(M)`.

**Comment by kellertuer** [comment]
hm, for `Euclidean` I directly ran into a problem, since the constructor takes `VarArgs{,Int,N}`, the type can not be optional neither before note after that. So is it ok to make a

`fieldtype` keyword argument?

**Comment by mateuszbaran** [comment]
Yes, `fieldtype` keyword argument is a good solution.

**Comment by kellertuer** [comment]
Well, we just have to come up with another name, since built in functions can not be extended, see https://docs.julialang.org/en/v1/base/base/#Core.fieldtype

but despite that it should work ;)

**Comment by mateuszbaran** [comment]
Maybe `Körpertyp` :smiley: ?

**Comment by kellertuer** [comment]
If the think of `eltype` indicating the element of an complex/real-valued array, then we might call it `pointtype` or `pttype` to indicate the point of a complex/real-valued manifold?

**Comment by mateuszbaran** [comment]
`eltype` mean "type of an element", so `pointtype` would mean "type of a point", which is not the same thing as the field. Another option would be `manifold_field` since we already have `manifold_dimension`.

**Comment by kellertuer** [comment]
Ah, then I would prefer `manifold_field`.

**Comment by kellertuer** [comment]
With the new type as proposed in #62 this can be closed and we continue in that issue.
