### ISSUE TITLE
[RFC] Graph manifold

### ISSUE THREAD

**Issue by kellertuer** [JuliaNLSolvers/Manifolds.jl#65]
I would like to use the holidays to think about modelling another manifold that extends the `PowerManifold` to some extend: Manifold-valued data on a graph. The idea stems from [this](http://dx.doi.org/10.1137/17M1118567) paper and at that time was implemented in Matlab but I was never happy with the implementation. I started some ideas in Julia, but I would like to do that efficiently. It's actually a nice interplay of data on vertices and edges on a graph.

# The setting
Let G be a graph with V its set of vertices and E the set of edges (each edge having a start point end an end point from V) and M be a manifold. Then we have four types of data

* manifold-valued data on the vertices, i.e. f: V-> M
* manifold-valued data on the on the edges, i.e. g: E -> M
* tangent vectors on edges, i.e. W: E->TM
* tangent vectors on vertices, i.e. Z: V-> TM (which might not that much be used)

If we call the `GraphManifold` GM, the idea is, that for example `log(GM, f, g)` for two manifold-valued data sets on the vertices yields tangent vectors on the edges, namely for an edge (v,w) in E we get the term log_{f_v} g_w. We can then mimic (see literature above) the Graph Laplace by producing Z: V -> TM with Z(v) = sum of all edges that start in v of these logs (note they are all log_f(v) - terms. And for example then perform a `exp(GM,f,Z)`

# RFC

I am not 100% sure how such an approach works for manifold-valued data on the edges, but I am curious to ponder about that 

My main question for comments is: What is a good and efficient way to represent this? the data f can be done similar to the Power manifold, but the GM also has to store its graph (adjacency matrix for example). Here I would like to ask for ideas/comments what to use – [LightGraphs.jl](https://github.com/JuliaGraphs/LightGraphs.jl) for example?

**Comment by mateuszbaran** [comment]
I wonder how this relates to the noncommutative discrete differential geometry as described here: https://phorgyphynance.wordpress.com/ or here: https://ncatlab.org/ericforgy/files/mexico.pdf ?

Regarding efficient representation, what kinds of relatively complex operations would be the most common? Adding/deleting edges? Computing graph `log`s and `exp`s? Something else?

**Comment by kellertuer** [comment]
Summing over all adjacent edges to assign a vector to a vertex is maybe also something. The `exp(GM,f,Z)` can be seen as a classical one on the power manifold |V|.

**Comment by kellertuer** [comment]
And yes the graph can model a discrete differential geometry, but at first glance your two links look like they act on the integer lattice?

**Comment by mateuszbaran** [comment]
> Summing over all adjacent edges to assign a vector to a vertex is maybe also something. The `exp(GM,f,Z)` can be seen as a classical one on the power manifold |V|.

I guess it might be the best to start with something relatively simple, like a digraph from `LightGraphs.jl` with custom weights, represented for example by dict from node/edge to an array representing a point or a tangent vector. Alternatively node meta-information can be represented by a vector indexed by node numbers and edge meta-information can be represented by (potentially sparse) matrices. There is `MetaGraphs.jl` but the way they represent meta-information looks really performance-unfriendly (unless someone is going to do lots of adding or deleting of such meta-information).

> And yes the graph can model a discrete differential geometry, but at first glance your two links look like they act on the integer lattice?

As I understand, regular lattices are used just for demonstration of the simplest cases. You can look at section 2.1 of the pdf I've linked. @EricForgy might be able to provide some input here.

**Comment by kellertuer** [comment]
I think I would prefer `LightGraphs.jl`, storing the points in an array (of size of the number of points or edges) anyways. What I am not yet so sure about is how to distinguish data on edges(vertices when it comes to dispatch for exp/log/retractions etc.

**Comment by mateuszbaran** [comment]
> I think I would prefer `LightGraphs.jl`, storing the points in an array (of size of the number of points or edges) anyways.

An array would faster for reading and writing edge/vertex data but slower during graph modification. Anyway, it's also a good choice.

> What I am not yet so sure about is how to distinguish data on edges(vertices when it comes to dispatch for exp/log/retractions etc.

What do you mean by distinguishing data here?

**Comment by sethaxen** [comment]
I actually have a "graph manifold" type of application, though maybe it doesn't fit in to what you're proposing here.

I'm doing inference on ensembles of protein structures, which we can represent with a graph. A single protein structure can be decomposed into a set of connected rigid bodies, fixing the topology. We interpret the nodes as points on SE(3) (rigid body orientations, i.e. shifts), and we interpret the edges likewise as points on SE(3) (perturbations). We do this so we can construct a probability distribution on the protein by assigning distributions to the edges. We can relate that to observables such as atomic distance distributions by convolving the distributions along the path between two nodes. Since those distributions have parameters, in reality our manifold is a statistical manifold with Dirac mean transformations at the nodes and `Brownian`/`IsotropicDiffusion` distributions at the edges. But any draw from that distribution would live on the graph manifold.

**Comment by kellertuer** [comment]
I am not sure whether my exp/log ideas above apply (those mixing edges/vertices), but still even with the default exp/log (vertex-vertex or edge-edge as argument, which is pasically power manifold stuff) I think your application fits perfectly :)

**Comment by kellertuer** [comment]
> What do you mean by distinguishing data here?

I am not 100% sure whether that's necessary. The interesting part ist, that there are different interplays between vertex-data and edge-data. Let's see that in detail and take
* `x`, `y` as manifold-valued data on `V`
* `v` tangent to `x` so tangent-valued data on `V`)
* `a`, `b` manifold-valued data on `E`
* `w` a tangent-valued data on `E` corresponding to `a`

Then
* `exp(GM,x,v)` should be a `y` as manifold-valued vertex data (element wise exp on the vertices)
* `exp(GM,a,w)` the same on the edges, i.e. a `b` on the edges
* `log(GM,x,y)` yields edge-valued data `w`, where for any edge `(e,f)`, i.e. `e,f \in V` are vertices we store `w( (e,f) ) = log(M, x_e, y_f)` or is this inconsistent? Because even `log(GM,x,x)` would yield a nonzero `w` and that seems inconsistent. Otherwise, `log(GM,x,y)` could also be seen element (vertex-) wise. Then even more the first case need another function/name/types.

Similar issues arise for the log on the edges. So despite distinguishing data I maybe also mean different functions/names.

**Comment by mateuszbaran** [comment]
I think `exp` and `log` should primarily work on the whole graph manifold (vertices + edges). Operations on edges or vertices only could probably also be `exp` and `log`, differentiated by a keyword argument.

If you want to get tangent vectors on edges from points on vertices, that's not really a `log`. Maybe we should call it `node_log`? There could also be a `node_exp` that works the other way.

> * Because even `log(GM,x,x)` would yield a nonzero `w` and that seems inconsistent.

That's I think because this type of `log` doesn't make a vector space consistent with the corresponding `exp`.


By the way, do you consider the graph itself as an object shared between points and tangent vectors, not connected to the manifold object?

**Comment by kellertuer** [comment]
Oh, I actually _never_ had data on vertices **and** edges. Just vertices _or_ edges.

I consider the graph being a property of the manifold, i.e. it is a field of the `GraphManifold`.

**Comment by mateuszbaran** [comment]
> Oh, I actually _never_ had data on vertices **and** edges. Just vertices _or_ edges.

This is an important point 🙂 . Then we should probably have a type parameter that tells whether a graph manifold is a node-manifold or edge-manifold.

**Comment by kellertuer** [comment]
Hm, but (in my mind) the `GraphManifold` is both and it depends on which data (node data or edge data) as parameters or returns you have? At least in my Matlab and the first Skecth for Julia I had such different data types.

So to make it more precise – a `log(GMe,x,x)` would return an edge-valued data since `GMe` is an edge manifold (and it would be the logs to neighbors) and `log(GMv,x,x)` would be node-valued data (and the zero tangent) then?

The one point I am not sure about it is, whether it would maybe also be an argument of exp/log (if a `GraphManifold` is both edge and vertex-manifold) and the same for all others where it's not uniquely determined.

**Comment by mateuszbaran** [comment]
For one thing, a manifold is supposed to have a single dimension for all its points, and the dimensions of the edge-manifold and node-manifold are usually different. What would `manifold_dimension` return if it didn't know whether it represents nodes or edges?



> So to make it more precise – a `log(GMe,x,x)` would return an edge-valued data since `GMe` is an edge manifold (and it would be the logs to neighbors) and `log(GMv,x,x)` would be node-valued data (and the zero tangent) then?

Well, something similar to this. The vertex manifold should have both `log`s -- the node-valued one and the edge-valued one (although I'm not really convinced that calling the second one just `log` is a good idea).

**Comment by kellertuer** [comment]
Oh, the `manifold_dimension` argument is a good one. You convinced me, we should do two manifolds, then, either

* `GraphEdgeManifold` or `EdgeGraphManifold` (the second is ordered by size kind of)
* `GraphVertexManifold` or `VertexGraphManifold`

or one could to that as a parameter as `GraphManifold{Vertex,M}` and `GraphManifold{Edge,M}`, which would make it easier to extend to a `VertexEdge` (i.e. really data on both) or even something HyperGraph-kind (subsets of E) data.

What do you think about the naming?

And yes, maybe it's better to name for `log(GMe,x,x)` would be `incident_log`, which would also work for manifold-valued edge data `incident_log(GMv,a,b)`, where it could compute the mean for a vertex (of its incident edges) and return the sum of the logs from there to the edge-values.

**Comment by mateuszbaran** [comment]
I like having a single type `GraphManifold` with a type parameter that determines whether it's a vertex or edge manifold. This way the graph-related operations can be more easily shared between both.

I think `incident_log` is a good name for the second type of `log`.

> would also work for manifold-valued edge data `incident_log(GMv,a,b)`, where it could compute the mean for a vertex (of its incident edges) and return the sum of the logs from there to the edge-values.

What would that operation be useful for?

**Comment by kellertuer** [comment]
Cool! So we have the same preference on the `GraphManifold`.

I don't know what it's for, I just thought about what that operation might be and that sounds reasonable. Whether it's also useful – maybe. For someone.

**Comment by mateuszbaran** [comment]
By the way, I recently realized that it's likely possible to extend one of the neater tricks from my PhD thesis to graph manifolds. If you ever needed to find a path in a graph manifold that sort-of looks like a template path, there is a very cool way to find it. The "sort-of looks like" part refers to a Fisher-Rao type metric on a manifold of (discretized) curves.

**Comment by kellertuer** [comment]
Sounds quite cool, though I don't know yet where to use that ;)

**Comment by sethaxen** [comment]
What is a template path?

**Comment by mateuszbaran** [comment]
That's a known path-like graph manifold over the same basic manifold. It also works for simple DAGs instead of paths (then the algorithm would look for the closest pair of path in both graph manifolds).
