### ISSUE TITLE
Syntax for equipping a manifold with structure

### ISSUE THREAD

**Issue by sethaxen** [JuliaNLSolvers/Manifolds.jl#69]
We current have `MetricManifold`, which equips a `Manifold` with a `Metric`. And soon thanks to #68 we will have `GroupManifold`, which equips a manifold with an `AbstractGroupOperation`. I'd like to propose a simple syntax for "equipping" a manifold with a structure:

```julia
(g::Metric)(M::Manifold) = MetricManifold(M, g)
(op::AbstractGroupOperation)(M::Manifold) = GroupManifold(M, op)
```

This lets us have a convenient notation for equipping:
```julia
M = Rotations(3) |> MultiplicationOperation() |> LeftInvariantCanonicalMetric()
```

which is equivalent to
```julia
M = MetricManifold(GroupManifold(Rotations(3), MultiplicationOperation()), LeftInvariantCanonicalMetric())
```

but much clearer/more pleasant to read. Of course, we could choose another symbol.

**Comment by mateuszbaran** [comment]
Good idea, the pipe syntax looks quite nice here.
