### ISSUE TITLE
Unify documentation

### ISSUE THREAD

**Issue by kellertuer** [JuliaNLSolvers/Manifolds.jl#74]
In an effort to get the documentation into a unified format I am asking for a few ideas and comments.

currentyl we are often documenting `exp!`, which I would like to avoid/refactor to provide the user with a consistent documentation. I would like to propose the following – on the example of `exp` but indeed for all functions with both mutating and non-mutating forms as well as all functions that might have formulae involved that are nice to have in the documentation.

As @sethaxen demonstrated nicely I would like to add a docstring to `exp(M,args...)` for the manifold `M`that documents the mathematical formula and maybe a reference if it's not a textbook manifold/metric. With that all non-mutating functions have a nice documentation that shows up in the docs. The documentation should always also list the `t` argument as a case.
This yields a nice overview over available functions in a consistent format.

Additionally either in the page for the API (`ManifoldsBase.jl`) or on a seperate page (implementation details, or how-to-implement-your-onw-manifold.md) we could list the approach of implementing a mutating one that the non-mutating one uses (including the `similar_result` approach.

If you agree to this, I can use my time travelling to do a unifying rework on the documentation once the next manifolds are finished. I will then also look that the docs and most implementations follow the [Code style Blue](https://github.com/invenia/BlueStyle) guidelines (shall we add their icon/banner then in the readme?)

**Comment by mateuszbaran** [comment]
Yes, I think unifying the style of documentation is a good idea. I agree with this approach. I can make some documentation on adding new manifolds.

We can officially use the blue style guidelines (and I like that banner). As a part of updating our code to this style we should probably rename files to lower_case_with_underscores, although I'd wait with it until we have fewer open PRs as renaming files may cause lots of conflicts.

**Comment by sethaxen** [comment]
I like this plan!

> As a part of updating our code to this style we should probably rename files to lower_case_with_underscores, although I'd wait with it until we have fewer open PRs as renaming files may cause lots of conflicts.

Is this part of blue style? The general rule I like is that a filename might be camel-case if a single type is declared in it, but that would rule out a number of our manifolds cases, since auxiliary types are sometimes declared. So I agree that for uniformity, snake-case might be the right way to go.

I also am sitting on a massive PR to standardize docstrings/code formatting and make them follow blue style, but I'm sitting on that until things settle a little more.

**Comment by mateuszbaran** [comment]
> > 
> 
> Is this part of blue style? The general rule I like is that a filename might be camel-case if a single type is declared in it, but that would rule out a number of our manifolds cases, since auxiliary types are sometimes declared. So I agree that for uniformity, snake-case might be the right way to go.

No, I haven't seen anything about file naming in the blue style guide but I'd like to have some consistent rules for naming files. We can have one main file per manifold that uses CamelCase but then it should be documented somewhere (although using snake_case everywhere looks a bit more consistent).

**Comment by kellertuer** [comment]
Currently the scheme seems to be roughly “manifolds in camel case others in snake case”. I would be fine with a subfolder manifolds to divide it and then go to camel case for example for all files? I like camel case for example for `SymmetricPositiveDefinite.jl` compared to its snake case for the manifold. Also that way file names of manifolds are consistent with their types.

**Comment by mateuszbaran** [comment]
> Currently the scheme seems to be roughly “manifolds in camel case others in snake case”. I would be fine with a subfolder manifolds to divide it and then go to camel case for example for all files? I like camel case for example for `SymmetricPositiveDefinite.jl` compared to its snake case for the manifold. Also that way file names of manifolds are consistent with their types.

OK, having a separate folder for manifolds and using CamelCase for files there looks fine.
