### ISSUE TITLE
Enhancements to group actions

### ISSUE THREAD

**Issue by sethaxen** [JuliaNLSolvers/Manifolds.jl#81]
`apply` and `translate` have a lot of similarities. Both apply elements of a group to act on a manifold, with `translate` being a special case where the action is the group operation. For semidirect product groups, where one must specify how one group acts on the other, we will need actions to have some of the extra functionality that translations have, namely inverse actions, differential of the action, and differential of the inverse action. Moreover, while the signature for translations puts the element doing the translating on the left, while the signature for actions puts the element acting on the right.

I'd like to unify these 2 interfaces. I'm thinking of making a `GroupOperationAction{TG,TAD}` that wraps a group. `apply!` with this action would always forward to `translate!`. Likewise the new `inverse_apply!`, `apply_diff!`, and `inverse_apply_diff!` would forward to their corresponding translation interfaces. I'd also like to make the two signatures more similar by moving the action element to the left.

@mateuszbaran how does this sound?

**Comment by mateuszbaran** [comment]
This sounds right, I saw the similarity but did not think about it that much. Canonical action of a group on itself is a good thing to have. The group interface itself remains separate and that's good. I'm OK with moving the action element to the left.

I'd be happy to see these semidirect products, I've implemented a few explicitly but having it partially automated would be nice 🙂 .
