### ISSUE TITLE
Forward more functions to decorated manifolds

### ISSUE THREAD

**Issue by sethaxen** [JuliaNLSolvers/Manifolds.jl#84]
Currently, only `base_manifold`, `representation_size`, and `manifold_dimension` for decorator manifolds are forwarded to the base manifold. This means that when decorator manifolds like `ArrayManifold`, `MetricManifold`, and `GroupManifold` are implemented, for any of the other methods like `zero_tangent_vector` or `isapprox` to be called, then they must be explicitly reimplemented for the decorator manifold to forward.

I think a more useful pattern is to forward most functions by default and let the decorator override that behavior if necessary. e.g. `MetricManifold` will override any methods that depend on a concept of a metric. This ensures that when one e.g. wraps `Rotations` in  a `GroupManifold` to get `SpecialOrthogonal` then one can still has the functionality of `Rotations` such as `inner`.

For decorator-specific methods like `local_metric` or `compose`, they can have a pattern like this:

```julia
my_fun(::MyDecorator, args...) = ...
function my_fun(M::Manifold, args...)
    is_decorator_manifold(M, args...) && return my_fun(base_manifold(M), args...)
    error("my_fun not implemented for $(M) and $(args)")
end
my_fun(M::MyWipingDecorator, args...) = error("my_fun not implemented for $(M) and $(args)")
```
This would unwrap decorators until one of the manifolds supports a function or error when it reaches one that removes functionality. This would make e.g. an `ArrayManifold{GroupManifold}` behave similarly to a `GroupManifold{ArrayManifold}` for the core functions and make the manifolds a bit more robust to different orders of decoration (though perhaps we should just support one).

**Comment by mateuszbaran** [comment]
I think it's fine to have a specific order the decorators have to be applied in, currently I think it is `GroupManifold(ArrayManifold(MetricManifold(M)))`, any of them can be omitted. Right now it's all about being able to swap `GroupManifold` with `ArrayManifold` because `MetricManifold` has to be in the same place.

I am conflicted about this proposal. On one hand it's quite hard to write correct forwarding and for example `ArrayManifold` doesn't do this totally right (for example it doesn't forward `vector_transport_to`). It would be nice to have a more robust approach to forwarding. On the other hand, it feels like quite a bit of work just to be able to swap `ArrayManifold` and `GroupManifold` since we are unlikely to get new decorators anytime soon. I'd wait with working on this proposal until we have an idea for a new decorator.

**Comment by sethaxen** [comment]
> I think it's fine to have a specific order the decorators have to be applied in, currently I think it is `GroupManifold(ArrayManifold(MetricManifold(M)))`, any of them can be omitted.

Even in that order, there are insufficient forwards. e.g. methods like `local_metric`, which explicitly require that a `MetricManifold` be passed. Likewise, `GroupManifold` doesn't forward `inner`, `exp`, `zero_tangent_vector`. So in practice, one can often only use one decorator at a time.
Either way, to me it makes the most sense to put `ArrayManifold` as the outermost decorator, since one can never guarantee that a decorator won't override functionality, and that way any core function we implement can have semantic checks.

> for example `ArrayManifold` doesn't do this totally right (for example it doesn't forward `vector_transport_to`).

Oh, is that just a missing forward, or is there a reason for that?

> Right now it's all about being able to swap `GroupManifold` with `ArrayManifold` because `MetricManifold` has to be in the same place.

No, I would like to as much as possible enable one to use the order that makes the most sense for their applications. I don't see why `MetricManifold` needs to be the innermost decorator. As I see it, `MetricManifold` should reset the defaults on all metric-related functions. I have applications where `SpecialEuclidean` can be equipped with several different metrics, some of which are left- or right-invariant. Some don't use the group structure at all. For these cases, it makes the most sense to first construct a `SpecialEuclidean` (which is an alias for `SemidirectProductGroup` with specific arguments) and _then_ decorate it with a metric. With the current approach, there is no good way to do this without heavy code duplication or constantly unwrapping the decorators to use some functionality.

We actually have more decorators than these though. Technically every `AbstractGroupAction` is a decorator for an `AbstractGroupManifold` that simply equips it with additional functionality. This is reflected in the introduction of `base_group`, which duplicates the function of `base_manifold`, and implementing the `compose` functions to forward to the decorated group.

As I see it, decoration is analogous to "equipping". Ideally it would only add functionality/geometric structure, not replace it, but since we e.g. implement some manifolds with default metrics, then `MetricManifold` resets some functionality. With this view, I think forwarding until an error is raised is a good way to go.

**Comment by kellertuer** [comment]
If the order should not matter, we can just do an `undecorate` or an `undecorate_to` (with a type we are looking for)?

**Comment by mateuszbaran** [comment]
> Even in that order, there are insufficient forwards. e.g. methods like `local_metric`, which explicitly require that a `MetricManifold` be passed. Likewise, `GroupManifold` doesn't forward `inner`, `exp`, `zero_tangent_vector`. So in practice, one can often only use one decorator at a time.
> Either way, to me it makes the most sense to put `ArrayManifold` as the outermost decorator, since one can never guarantee that a decorator won't override functionality, and that way any core function we implement can have semantic checks.

Yes, right, we have many missing forwards, and I have nothing against forwarding more methods for specific decorator where that makes sense.

Right, `ArrayManifold` can also be outermost. With `ArrayManifold` in the outermost position I'd expect it to also check the arguments and results to `compose`, `inv`, etc.

> > for example `ArrayManifold` doesn't do this totally right (for example it doesn't forward `vector_transport_to`).
> 
> Oh, is that just a missing forward, or is there a reason for that?

Just one of the missing forwards.

> No, I would like to as much as possible enable one to use the order that makes the most sense for their applications. I don't see why `MetricManifold` needs to be the innermost decorator. As I see it, `MetricManifold` should reset the defaults on all metric-related functions. I have applications where `SpecialEuclidean` can be equipped with several different metrics, some of which are left- or right-invariant. Some don't use the group structure at all. For these cases, it makes the most sense to first construct a `SpecialEuclidean` (which is an alias for `SemidirectProductGroup` with specific arguments) and _then_ decorate it with a metric. With the current approach, there is no good way to do this without heavy code duplication or constantly unwrapping the decorators to use some functionality.

That's an interesting case I didn't think about. It's a good justification for wrapping `GroupManifold`s in `MetricManifold`s, so group operations should be forwarded through `MetricManifold`.

> We actually have more decorators than these though. Technically every `AbstractGroupAction` is a decorator for an `AbstractGroupManifold` that simply equips it with additional functionality. This is reflected in the introduction of `base_group`, which duplicates the function of `base_manifold`, and implementing the `compose` functions to forward to the decorated group.

`AbstractGroupAction` isn't technically a `Manifold` though. It doesn't derive from any types and because it also wraps a G-manifold I don't think any manifold-related functionality can be forwarded (only the group-related functionality).

> As I see it, decoration is analogous to "equipping". Ideally it would only add functionality/geometric structure, not replace it, but since we e.g. implement some manifolds with default metrics, then `MetricManifold` resets some functionality. With this view, I think forwarding until an error is raised is a good way to go.

> If the order should not matter, we can just do an `undecorate` or an `undecorate_to` (with a type we are looking for)?
> 
> Edit: I meant that to get to the point that the order of decorators is irrelevant.

I'll try to summarize what I think about it now:

  1. I agree that group-related operations should be forwarded through `MetricManifold`, maybe even all decorators by default. Makes sense.
  2. `ArrayManifold` should probably check arguments and results of group-related functionality instead of plain forwarding.
  3. Order of decorators can't be totally irrelevant, primarily because it'd be quite hard for `ArrayManifold` to enforce checking of operations that wrap around it (`MetricManifold(ArrayManifold(...))` or `GroupManifold(ArrayManifold(...))`).
  4. Pure forwarding of manifold-related functionality is currently limited to `GroupManifold`. I'm not against making pure forwarding the default for all decorators but I'm not convinced it's actually helpful at the moment.

**Comment by sethaxen** [comment]
> Right, `ArrayManifold` can also be outermost. With `ArrayManifold` in the outermost position I'd expect it to also check the arguments and results to `compose`, `inv`, etc.

Yes, as we add functions to ManifoldsBase, they should get `ArrayManifold`-specific forwards.

> That's an interesting case I didn't think about. It's a good justification for wrapping `GroupManifold`s in `MetricManifold`s, so group operations should be forwarded through `MetricManifold`.

Yes, we'll need to think carefully about how to handle metrics for groups, but some of these cases will probably require `MetricManifold` wrapping `GroupManifold`. I'll write up an issue with some ideas we can discuss.

> `AbstractGroupAction` isn't technically a `Manifold` though. It doesn't derive from any types and because it also wraps a G-manifold I don't think any manifold-related functionality can be forwarded (only the group-related functionality).

No, certainly it doesn't implement the types, but my point is that it effectively decorates the group, not the G-manifold. Action elements are elements of the group, and every element of the group is an element of the action. In other words, we could absolutely have implemented it as an `ActionManifold` that wraps a group and an `AbstractGroupAction` and then dispatch on the group and action, by direct analogy to how we dispatch on the base manifold and operation for a `GroupManifold`. In fact, that would save us a few method implementations.

> I'll try to summarize what I think about it now:

I think we're on the same page for points 1-3. I disagree on 4, but I don't think this is urgent. I'll start by making `identity`, `inv`, `compose`, `translate`, `inverse_translate`, `translate_diff`, `inverse_translate_diff`, and their mutating variants all forward to the decorated manifold by default here, and we can revisit this later.

> If the order should not matter, we can just do an `undecorate` or an `undecorate_to` (with a type we are looking for)?

I like the idea of having something like `base_manifold` that doesn't unwrap all decorators. `base_manifold` in the cases I've checked can unwrap many decorators at compile time. If we can implement `undecorate_to` the same way, that would probably make the kind of forwarding I'm talking about a lot easier, when a function is tied to a specific manifold type (e.g. that would be useful for group operations but not naively for metric ones, since metric functions could be implemented on the base manifold).

**Comment by mateuszbaran** [comment]
> Yes, we'll need to think carefully about how to handle metrics for groups, but some of these cases will probably require `MetricManifold` wrapping `GroupManifold`. I'll write up an issue with some ideas we can discuss.

Sure, great :slightly_smiling_face: 

> No, certainly it doesn't implement the types, but my point is that it effectively decorates the group, not the G-manifold. Action elements are elements of the group, and every element of the group is an element of the action. In other words, we could absolutely have implemented it as an `ActionManifold` that wraps a group and an `AbstractGroupAction` and then dispatch on the group and action, by direct analogy to how we dispatch on the base manifold and operation for a `GroupManifold`. In fact, that would save us a few method implementations.

Yes, that's an option, although to me it wouldn't feel right.

> I think we're on the same page for points 1-3. I disagree on 4, but I don't think this is urgent. I'll start by making `identity`, `inv`, `compose`, `translate`, `inverse_translate`, `translate_diff`, `inverse_translate_diff`, and their mutating variants all forward to the decorated manifold by default here, and we can revisit this later.

OK, I don't have a particularly strong feelings about 4, I just don't see the benefit right now. If you want to work on it, then sure, we can have pure forwarding of manifold-related functions by default.

**Comment by kellertuer** [comment]
To continue a discussion started in #104 (where it did not belong, sorry) - my main point was the folloing: Let's look at one of the functions in `groups.jl namely `translate:

```julia
translate(M::Manifold, x, y) = translate(M, x, y, LeftAction())
function translate(M::Manifold, x, y, conv::ActionDirection)
    return translate(M, x, y, conv, is_decorator_manifold(M))
end
function translate(M::Manifold, x, y, conv::ActionDirection, ::Val{true})
    return translate(M.manifold, x, y, conv)
end
function translate(M::Manifold, x, y, conv::ActionDirection, ::Val{false})
    return error("translate not implemented on $(typeof(M)) for elements $(typeof(x)) and $(typeof(y)) and direction $(typeof(conv))")
end
function translate(G::AbstractGroupManifold, x, y, conv::ActionDirection)
    return compose(G, _action_order(x, y, conv)...)
end

translate!(M::Manifold, z, x, y) = translate!(M, z, x, y, LeftAction())
function translate!(M::Manifold, z, x, y, conv::ActionDirection)
    return translate!(M, z, x, y, conv, is_decorator_manifold(M))
end
function translate!(M::Manifold, z, x, y, conv::ActionDirection, ::Val{true})
    return translate!(M.manifold, z, x, y, conv)
end
function translate!(M::Manifold, z, x, y, conv::ActionDirection, ::Val{false})
    return error("translate! not implemented on $(typeof(M)) for elements $(typeof(x)) and $(typeof(y)) and direction $(typeof(conv))")
end
function translate!(G::AbstractGroupManifold, z, x, y, conv::ActionDirection)
    return compose!(G, z, _action_order(x, y, conv)...)
end
```
which takes 27 lines. Why can't we (like for `exp` and `exp!`) replace the first 10 (or even 13? I think even 13) lines by
```julia
function translate(M::Manifold, x, y)
  z = allocate(...)
  return translate!(M,z,x,y)
end
```

and from the same regime - is it necessary to overwrite `exp`? When this gets called with a group action, it still passes down to `exp!` and that's properly overwritten. Similarly for a few functions in the beginning.

In general, I was thinking about generalizing `base_manifold` with a level such that one can also just remove the outer level. so `base_manifold(M)` would still strip all decorators, `base_manifold(M; level=1)`would strip one decorator and one could even do `base_manifold(M; strip=MetricManifold)` which would go through the decorators and just remove all metrics. If (and I have never worked with those). maybe that'll also help a few definitions?
