### ISSUE TITLE
Invariant metrics on groups

### ISSUE THREAD

**Issue by sethaxen** [JuliaNLSolvers/Manifolds.jl#89]
I think the default behavior of metric-dependent functions like `inner`, `exp`, and `log` on a `GroupManifold` should be to forward to the base manifold, i.e. by default groups use the default metric of the base manifold. They can be equipped with a generic metric like any manifold, but they can also be equipped a custom metric using the group structure.

Given a group `G`, an automorphism `τ` of the group on itself (i.e. left or right-translation), and a metric `g` on the Lie algebra, we can define a `τ`-invariant metric with inner product

```
g_x(v, w) = g_e(dτ_x^{-1} v, dτ_x^{-1} w),
```

We can thus evaluate this inner product everywhere and numerically integrate the geodesics. When the metric is bi-invariant, then we can also define the Riemannian logarithm and exponential in terms of the same maps at the tangent space, which in this case coincide with the Lie logarithm and exponential:

```math
\begin{aligned}
\exp_x &= τ_x \circ \exp_e \circ dτ_x^{-1}\\
\log_x &= dτ_x \circ \log_e \circ τ_x
\end{aligned}
```

The proposed new types are:

```julia
struct InvariantMetric{G,D} <: Metric
    metric::G
    direction::D
end
function InvariantMetric(metric::Metric, conv::ActionDirection = LeftAction())
    return InvariantMetric{typeof(G),typeof(conv)}(metric, conv)
end
const LeftInvariantMetric{G} = InvariantMetric{G,RightAction}
const RightInvariantMetric{G} = InvariantMetric{G,LeftAction}
```

where `G` is a metric on the Lie algebra.

When one knows that a given metric on a given group is bi-invariant, one can simply overload `exp!` to point to `gexp!` or `group_exp!` or whatever we name it and likewise `log!` to `glog!` or `group_log!`.

**Comment by mateuszbaran** [comment]
I like that by default `GroupManifold` forwards manifold-related operations to decorated manifold. Having left- and right-invariant metrics as separate decorators looks like the correct approach.

> When one knows that a given metric on a given group is bi-invariant, one can simply overload `exp!` to point to `gexp!` or `group_exp!` or whatever we name it and likewise `log!` to `glog!` or `group_log!`.

This is, I think, the problematic part of the proposal. Both left- and right- invariant inner products define some metrics on the manifold, sometimes different ones. If the metric is not bi-invariant, the group exponential will again be different from Riemannian exponential.

What I would naively expect is that when I wrap a `GroupManifold` in `LeftInvariantMetric`, then the metric defined by the inner product on the Lie algebra reached through differential of the left translations will be used for all metric-related functions (exp, log, vector transport, etc.) Does it make sense? Is there a reasonable way to define `log` for such metric?

**Comment by sethaxen** [comment]
> What I would naively expect is that when I wrap a `GroupManifold` in `LeftInvariantMetric`, then the metric defined by the inner product on the Lie algebra reached through differential of the left translations will be used for all metric-related functions (exp, log, vector transport, etc.) Does it make sense? Is there a reasonable way to define `log` for such metric?

Yes, this is what I'm proposing. Having defined an inner product, all of our `MetricManifold` defaults will use that inner product. By default `exp` will be numerically integrated, and `log` will be unimplemented until we have a default like geodesic shooting.

I did quite a bit of reading, and from what I can tell, the geodesics don't in general have a close relationship with the group exponential/log; it's only in the bi-invariant case that they do. So we will need to fall back to our defaults.

```
\begin{aligned}
\operatorname{retr}_x &= τ_x \circ \operatorname{retr}_e \circ dτ_x^{-1}\\
\operatorname{retr}^{-1}_x &= dτ_x \circ \operatorname{retr}^{-1}_e \circ τ_x
\end{aligned}
```

These are I believe valid retractions. We can therefore use the differential of translation to turn the `log` and `exp` at the Lie algebra into a retraction at any point, and this could even be the default. I don't know how useful this would be though.

**Comment by mateuszbaran** [comment]
> Yes, this is what I'm proposing. Having defined an inner product, all of our `MetricManifold` defaults will use that inner product. By default `exp` will be numerically integrated, and `log` will be unimplemented until we have a default like geodesic shooting.

OK, sounds good :+1: .

> These are I believe valid retractions. We can therefore use the differential of translation to turn the `log` and `exp` at the Lie algebra into a retraction at any point, and this could even be the default. I don't know how useful this would be though.

This can be useful if the log/exp maps at group identity turn out to be simpler than general versions.

**Comment by sethaxen** [comment]
> This can be useful if the log/exp maps at group identity turn out to be simpler than general versions.

When the log/exp maps at the identity using the differential of translation are the same as the log/exp maps at a point (i.e. when the metric is bi-invariant), then the default for `exp`/`log` will be to perform the map at the identity. I only question the utility of of this retraction when the metric is _not_ bi-invariant.
