### ISSUE TITLE
Metrics and pseudo-Riemannian manifolds

### ISSUE THREAD

**Issue by sdaxen** [JuliaNLSolvers/Manifolds.jl#9]
Various methods like `exp`, `log`, `dot`, `norm`, `geodesic`, etc only make sense in the context of a manifold equipped with a Riemannian metric. In practice, one may want to apply several different metrics to a manifold without reimplementing everything about the manifold. How do we want to implement this functionality?

I wonder if it's a good idea to have something like

```julia
abstract type Metric end
abstract type RiemannianMetric end

struct PseudoRiemannianManifold{M<:Manifold,G<:Metric} <: Manifold
    m::M
    g::G
end

metric(m::PseudoRiemannianManifold) = m.g
tensor_matrix(g::Metric, x) = error("not implemented")
dot(g::Metric, x, v, w) = dot(v, tensor_matrix(g, x) * w)
dot(m::PseudoRiemannianManifold, x, v, w) = dot(metric(m), x, v, w)
...
```

Of course, one could specialize various functions for more efficiency.

**Comment by kellertuer** [comment]
I like that approach, since the metric will only be saved if we need that.
Should'n the second line read `abstract type RiemannianMetric <: Metric end`?

And we could also do a manifold, where we also store the metric but get really a Riemannian manifold, and where we either dispatch on the metric, too, or one can use the metric, i.e. in the geodesic to solve the corresponding PDE. So in short: This approach seams also a good idea for `RiemannianManifoldWithMetric` (not a nice name yet), where maybe no closed form for some functions are available.

**Comment by mateuszbaran** [comment]
What functions would apply to non-pseudoriemannian manifolds? (apart from `dimension`)

**Comment by sdaxen** [comment]
Differentiable manifolds not equipped with a metric still have properties of dimension, (co)tangent space/bundle, curves, compactness, connectedness, etc. The whole machinery of tangent bundles/product manifolds/power manifolds would still apply to manifolds without specifying a metric. Some of these we will probably want to support (e.g. a trait `iscompact`). We could also have functions like `istangent` and `ispoint` that don't require any notion of metric.

And we may want to provide interfaces for other geometric structures such as symplectic structures that are completely distinct from the metric structure.

Since any manifold with a metric is a `PseudoRiemannianManifold`, we could also call this a `MetricManifold` (since a Riemannian manifold _is_ a pseudo-Riemannian manifold. We can always dispatch on whether a manifold is Riemannian by dispatching on its metric being Riemannian. A trait could make this simpler. e.g.

```julia
using SimpleTraits
@traitdef IsRiemannian{X}
@traitimpl IsRiemannian{X} <- isriemannian(X)
isriemannian(X::Manifold) = false
isriemannian(X::PseudoRiemannianManifold{M,G}) where {M<:RiemannianMetric,G} = true
```

> Should'n the second line read `abstract type RiemannianMetric <: Metric` end?

Oh of course, sorry about that.

@kellertuer I'm not sure I'm following regarding `RiemannianManifoldWithMetric`. Would this be a manifold that a user creates storing a metric but not a `PseudoRiemannianManifold`? What is a use case for this?

An alternative interface:

```julia
abstract type Metric{M<:Manifold} end

abstract type RiemannianMetric{M} <: Metric{M} end

struct EuclideanMetric{M} <: RiemannianMetric{M}
   m::M
end

struct Euclidean <: Manifold end
struct Sphere <: Manifold end

dot(g::EuclideanMetric, x, v, w) = dot(v, w)
exp(g::EuclideanMetric{M}, x, v) where {M<:Euclidean} = x + v
exp(g::EuclideanMetric{M}, x, v) where {M<:Sphere} = ...
```

The advantage to this approach is that we don't have to worry about forwarding operators like `iscompact` from `PseudoRiemannianManifold` to its wrapped manifold, and we can provide specializations for common induced metrics such as the Euclidean metric. What I don't like about it is that if one wants to work with a manifold with a specific metric a lot (which is probably most cases), you end up storing the manifold wrapped in the metric.

**Comment by kellertuer** [comment]
The use was again merely thought semantically, i.e. to know whether your manifold is Riemannian or just pseudo metric. I had not yet an application in mind - but maybe also with view to the Lie groups, where one could distinguish bi-invariant metrics - ...
Your approach just sketched with typed metrics does all ideas I had – so I am quite in favour of the alternative approach.

**Comment by sdaxen** [comment]
#12 provided all of the functionality discussed here. We can open new issues for additional functionality.
