### ISSUE TITLE
Add function for field dimension

### ISSUE THREAD

**Issue by sethaxen** [JuliaNLSolvers/Manifolds.jl#90]
Several manifolds are defined over fields, where the dimension of the manifold is dependent on the dimension of the field, i.e. the size of the smallest real space that the field can be identified with (frankly, I'm surprised Julia base doesn't have such a function). Rather than reimplementing `manifold_dimension` for every field/manifold combination, implement whenever possible a generic `manifold_dimension` that depends on the dimension of the field. Then add the following methods

```julia
field_dimension(::RealNumbers) = 1
field_dimension(::ComplexNumbers) = 2

manifold_dimension(::Euclidean{N,𝔽}) where {N,𝔽} = *(field_dimension(𝔽), N.parameters...)
manifold_dimension(::SymmetricMatrices{N,𝔽}) where {N,𝔽} = field_dimension(𝔽) * div(N*(N+1),2)
manifold_dimension(::Stiefel{M,N,𝔽}) where {M,N,𝔽} = field_dimension(𝔽) * (M*N - div(N*(N-1), 2)) - N
manifold_dimension(::FixedRankMatrices{M,N,k,𝔽}) where {M,N,k} = field_dimension(𝔽) * (M+N-k) * k
manifold_dimension(::Grassmann{N,K,𝔽}) where {N,K,𝔽} = field_dimension(𝔽)*K*(N-K)
```

To introduce a new field, e.g. quaternions, a user can then just add
```julia
struct QuaternionNumbers <: AbstractField end
field_dimension(::QuaternionNumbers) = 4
```
(To be honest, we should probably just add `QuaternionNumbers`, since adding it doesn't require us to pick any one implementation of quaternions)

**Comment by kellertuer** [comment]
I think this is fine, for those manifolds where the dimensions differ more than just by this factor two, one can still overwrite both cases individually. The `manifold_dimensions` of course belong into the  seperate files (so maybe wait for my nearly finished rework).
