### ISSUE TITLE
Representing and converting points on a `PowerManifold`.

### ISSUE THREAD

**Issue by kellertuer** [JuliaNLSolvers/Manifolds.jl#93]
Currently any point on a PowerManifold is represented as an array, i.e. a Point on `PowerManifold(Sphere(2),4,5)` is an array `Array{T,3}` of size `(3,4,5)`, since points on the sphere are `Array{T,1}` of size `(3,)`. While I can see that this in internally nice and efficient, I would like to think of them more like an `Array{Array{T,1},2}`. where the inner arrays are all of `(3,)` and the outer one is of size `(4,5)`.

I am fine with an internal representation like that, but in accessing single points like `p[2,3]` in the above case I would like to get the second (of the 4) and third (of the 5)s point which is then an `(3,)` itself. Can we do something like that (at least for convenience – I am not proposing to change internal storage necessarily)?

**Comment by kellertuer** [comment]
One thing that should be easy is, if you have points on a manifold, say `a,b,c,d,e,f` on `Sphere(2)` and they are in a `2x3` image, i.e. `x` is a `Array{Array{T,1},2}` with these inside, then `power_represent` could do something like `ProductRepr` (though I was surprised that is not defined within `ProductManifold` file-wise). and one could do `power_access(M,x,2,3)` to solve above issue for example, so it's merely asking for an interface.

Stacking Power into single arrays, while efficient access-wise, might be confusing for a `Power(Power(M))` for the user though (while I would also not necessarily recommend that anyways ;)).

**Comment by mateuszbaran** [comment]
There are three separate issues here:
1. `PowerManifold` should support nested representation of points. It's relatively easy, although representation would have to be included in manifold type to be able to implement `representation_size`. It's important also because not all manifolds have array representation.
2. We should have a function for converting between nested and multi-dimensional representations of points on a power manifold.
3. Something like `power_access` would be useful, right.

I'll work on it later.

**Comment by kellertuer** [comment]
Great! I can still write the tests with the `GraphManifold` using non-nested ones now that I understood the ideas, but having nested representations would be awesome – and yes the `representation_size` is then a little tricky, so the Manifold should be aware of the representation.

**Comment by sethaxen** [comment]
What if we adapted `submanifold_component` and `submanifold_components` for this (i.e. using the new methods in #82?

**Comment by mateuszbaran** [comment]
Hmm... maybe? I've taken a look at our code for the power manifold and `_read` accesses a component like that, although it needs one extra argument to be efficient for the current representation. What would `submanifold_components` actually return here?

**Comment by mateuszbaran** [comment]
I've started working on this a bit. The most difficult part is modifying `similar_result` to work with a nested representation. This will require some changes in ManifoldsBase.jl.

**Comment by sethaxen** [comment]
> Hmm... maybe? I've taken a look at our code for the power manifold and `_read` accesses a component like that, although it needs one extra argument to be efficient for the current representation. What would `submanifold_components` actually return here?

I'm not certain. It just seems that we have a number of functions that are doing very similar things and there might be an opportunity to unify into a small set of general functions that may also be useful elsewhere.

**Comment by mateuszbaran** [comment]
Done in #98 .
