### ISSUE TITLE
Run JuliaFormatter on source files

### ISSUE THREAD

**Issue by sethaxen** [JuliaNLSolvers/Manifolds.jl#94]
I've been running [JuliaFormatter](https://github.com/domluna/JuliaFormatter.jl) on new source files before committing. While it doesn't/can't enforce all of BlueStyle's recommendations, the formatting decisions it does make are compatible with BlueStyle and are quite nice. Running it ensures uniform style, even for things we miss. Also at some point in the future, we may be able to make format testing a part of our pipeline, like folks in Python can do with `black`.

 I think we'll just need one big PR that runs JuliaFormatter on all files. One formatting decision that this will change is the choice to switch from one import per line to multiple imports per line (JuliaFormatter prefers the latter, but this is actually a [BlueStyle convention](https://github.com/invenia/BlueStyle#module-imports); it makes diffs easier to read).

**Comment by mateuszbaran** [comment]
OK, we can use JuliaFormatter.

**Comment by sethaxen** [comment]
Okay, once #82 and #86 are merged, I'll submit a PR, since they make changes to quite a few existing files.
